[package]
name = "bevy-ui-dsl"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Anti-Alias"]
description = "A DSL library that simplifies the creation of widgets for bevy_ui."
repository = "https://github.com/Anti-Alias/bevy_ui_dsl"
homepage = "https://github.com/Anti-Alias/bevy_ui_dsl"
keywords = ["bevy", "dsl", "gui", "gamedev"]
categories = ["gui", "game-development"]
readme = "README.md"

[dependencies]
bevy_ui = { git = "https://github.com/bevyengine/bevy", features = ["bevy_text"] }
bevy_text = { git = "https://github.com/bevyengine/bevy" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy" }
bevy_asset = { git = "https://github.com/bevyengine/bevy" }
bevy_render = { git = "https://github.com/bevyengine/bevy" }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }

[features]
class_helpers = []
